name: CI Pipeline for microservices x y z

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Checkout and Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up the JDK version 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache the dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

  build-test:
    name: Build microservices and unit test microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [microservicex, microservicey, microservicez]
    steps:
      - uses: actions/checkout@v3

      - name: Build and test ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: |
          mvn clean install

  integration:
    name: Integration Testing
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build JARs for all microservices
        run: |
          mvn clean package -f services/microservicex/pom.xml
          mvn clean package -f services/microservicey/pom.xml
          mvn clean package -f services/microservicez/pom.xml

      - name: Spin up microservices for integration test
        run: docker-compose -f docker-compose.integration.yml up -d

      - name: Run integration tests
        working-directory: ./services/microservicex  
        run: mvn verify

  package:
    name: Package All Microservices
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package microservicex
        working-directory: ./services/microservicex
        run: mvn package -DskipTests

      - name: Package microservicey
        working-directory: ./services/microservicey
        run: mvn package -DskipTests

      - name: Package microservicez
        working-directory: ./services/microservicez
        run: mvn package -DskipTests